(setenv "PATH" (concat "/usr/texbin:/usr/local/bin:" (getenv "PATH")))
(setq exec-path (append '("/usr/texbin" "/usr/local/bin") exec-path))
(load "auctex.el" nil t t)
(load "preview-latex.el" nil t t)
(setq TeX-PDF-mode t)
(setq TeX-view-program-list '(("Shell Default" "open %o")))
(setq TeX-view-program-selection '((output-pdf "Shell Default")))
(add-hook 'LaTeX-mode-hook (lambda()
                             (add-to-list 'TeX-command-list
                                          '("PdfLaTeX" "%`pdflatex%(mode)%' %t" TeX-run-TeX nil t))
                             (setq TeX-command-default "PdfLaTeX")
                             (setq TeX-save-query  nil )
                             (setq TeX-show-compilation t)
                             ))
(provide 'auxtex-conf)
