(add-to-list 'load-path "~/.emacs.d/modules/")
(require 'elpa-conf)
(require 'misc-conf)
(require 'color-theme-conf)
(require 'eshell-conf)
(require 'markdown-mode-conf)
(require 'erc-conf)
(require 'lisp-mode-conf)
(require 'c-mode-conf)
(require 'key-bindings-conf)
(require 'scheme-mode-conf)
(require 'cpp-mode-conf)
(require 'ggtags-conf)
(load-file "~/.emacs.d/extensions/ProofGeneral/generic/proof-site.el")

(provide 'init)
