(add-to-list 'load-path "~/.emacs.d/modules/")
(require 'elpa-conf)
(require 'misc-conf)
(require 'color-theme-conf)
(require 'eshell-conf)
(require 'orgmode-conf)
(require 'markdown-mode-conf)
(require 'erc-conf)

(require 'lisp-mode-conf)
(require 'c-mode-conf)
(require 'scala-conf)
(require 'key-bindings-conf)

(provide 'init)
